var Data = [
  {
    id: 1,
    name: "Nike",
    imageSource: require("../../assets/women.webp"),
    imageSource1: require("../../assets/women1.webp"),
    imageSource2: require("../../assets/women2.webp"),
    details: "Women's Sneakers",
    price: 150,
    count: 0,
  },
  {
    id: 2,
    name: "Levi's",
    imageSource: require("../../assets/jeans.jpg"),
    imageSource1: require("../../assets/jeans1.webp"),
    imageSource2: require("../../assets/jeans2.jpg"),
    details: "Men's Denim Jeans",
    price: 100,
    count: 0,
  },
  {
    id: 3,
    name: "Nike",
    imageSource: require("../../assets/men.webp"),
    imageSource1: require("../../assets/men1.webp"),
    imageSource2: require("../../assets/men2.webp"),
    details: "Men's Red Sneakers",
    price: 200,
    count: 0,
  },
  {
    id: 4,
    name: "Samsung",
    imageSource: require("../../assets/s20.jpg"),
    imageSource1: require("../../assets/s201.webp"),
    imageSource2: require("../../assets/s202.jpg"),
    details: "Galaxy S20",
    price: 1000,
    count: 0,
  },
  {
    id: 5,
    name: "Nike Air",
    imageSource: require("../../assets/hat1.webp"),
    imageSource1: require("../../assets/hat2.webp"),
    imageSource2: require("../../assets/hat3.webp"),
    details: "Hat",
    price: 30,
    count: 0,
  },
];
module.exports = Data;
