var FashionData = [
  {
    id: 1,
    name: "Nike",
    imageSource: require("../../assets/Fashion/nike1.jpeg"),
    imageSource1: require("../../assets/Fashion/nike2.jpeg"),
    imageSource2: require("../../assets/Fashion/nike3.jpeg"),
    details: "The Nike Revolution 5 ",
    price: "150",
  },
  {
    id: 2,
    name: "ADIDAS ",
    imageSource: require("../../assets/Fashion/adidas1.jpeg"),
    imageSource1: require("../../assets/Fashion/adidas2.jpeg"),
    imageSource2: require("../../assets/Fashion/adidas3.jpeg"),
    details: "Solid Men Red T-Shirt",
    price: "100",
  },
  {
    id: 3,
    name: "Levi's",
    imageSource: require("../../assets/Fashion/levis1.jpeg"),
    imageSource1: require("../../assets/Fashion/levis2.jpeg"),
    imageSource2: require("../../assets/Fashion/levis3.jpeg"),
    details: "Slim Men Blue Jeans",
    price: "200",
  },
  {
    id: 4,
    name: "Harpa",
    imageSource: require("../../assets/Fashion/harpa1.jpeg"),
    imageSource1: require("../../assets/Fashion/harpa2.jpeg"),
    imageSource2: require("../../assets/Fashion/harpa3.jpeg"),
    details: "Solid Women Blue Top",
    price: "100",
  },
  {
    id: 5,
    name: "Titan",
    imageSource: require("../../assets/Fashion/titan1.jpeg"),
    imageSource1: require("../../assets/Fashion/titan2.jpeg"),
    imageSource2: require("../../assets/Fashion/titan3.jpeg"),
    details: "Karishma Analog Watch - For Men",
    price: "150",
  },
];
module.exports = FashionData;
